FROM menci/archlinuxarm:base-devel

RUN pacman -Syu --noconfirm && pacman -S --noconfirm openssl-1.1 rustup neovim git fish fisher zip unzip gzip lazygit clang llvm lldb rust-analyzer inetutils sccache npm ruby python

COPY config.toml /root/.cargo/config.toml

COPY setup-rust.sh setup-vim.sh ./

RUN ./setup-rust.sh

RUN ./setup-vim.sh

RUN mkdir /app

WORKDIR /app

